更新数据到2022年12月
lizy14/division-changes pull request #4
Opened 2023-12-15 06:50 UTC by Steve235lab

#3 

2. 使用Black重新格式化了代码
3. 更新了数据，最新的数据为2022年12月
4. 更新了文档中部分失效URL
5. 更新了脚本，现在通过相对路径引用项目文件，而不是依赖项目根目录环境变量

2023-12-15 07:29 UTC, lizy14 commented
非常感谢您对这个项目的贡献！

关于 `rules-handwritten/` 下面的修改，如果您仍有空闲时间，建议一并将作出这些修改所依据的文档提交到仓库，备查之用。例如 [`descriptions/source-b/2017.txt`](https://github.com/lizy14/division-changes/blob/master/descriptions/source-b/2017.txt)。我们有一个脚本 [`scripts/retrieve-descriptions.sh`](https://github.com/lizy14/division-changes/blob/690cc4b7c0d66577a9117bdb9b216abc38ab5b24/scripts/retrieve-descriptions.sh#L2C64-L2C64) 可以下载并处理这些文档。

2023-12-15 07:31 UTC, jianghc724 reviewed
Just took first glance, more review coming after I find environment to run your branch.

2023-12-15 07:31 UTC, jianghc724 commented on rules-generated/code-removals-unaccounted-for.log
> -1984-1985 142500 晋东南地区
这里对于之前的修改是出于什么原因？可否举例说明一下改动之后带来的结果改变？

2023-12-15 13:05 UTC, jianghc724 commented on README.md
> +* 1984年及以后，历年县级及以上行政区划代码表，民政部：https://www.mca.gov.cn/n156/n186/index.html
我刚刚查阅了一下这里的链接，不仅仅这里需要更新，目前来看scripts/retrieve-tables.sh下的链接也有很多失效了。
如果可以的话也可以在这个commit里进行更新，没有空闲的话我可以更新，感谢！

2023-12-15 13:16 UTC, Steve235lab commented
以上问题我晚些时候会跟进🤗
另外，我习惯了用Black Formatter进行格式化，如果大片的格式化变更影响code review，我可以revert那一次提交。

2023-12-18 02:44 UTC, jianghc724 commented
> 以上问题我晚些时候会跟进🤗 另外，我习惯了用Black Formatter进行格式化，如果大片的格式化变更影响code review，我可以revert那一次提交。

不影响code review，但是这些格式化可能会增加git blame的使用麻烦。不过对于这个repo，由于commit不多，我并不反对这些格式化。

2023-12-18 15:01 UTC, Steve235lab commented on rules-generated/code-removals-unaccounted-for.log
> -1984-1985 142500 晋东南地区
这部分是程序生成的在前一年存在，后一年消失了的代码，用于参考来确定哪些代码需要手动编写合、拆区规则。原本的文件中具有更多的内容，我推测是因为那个版本是在你们手动编写规则之前生成的，而我拿到的代码已经包含了你们编写的规则，所以这部分已经具有规则的代码在我执行的时候就不会被计入此文件。我认为这个文件作为中间结果，其中的内容没有太多的讨论价值，所以我准备将这个文件复原。

2023-12-18 15:12 UTC, Steve235lab commented on README.md
> +* 1984年及以后，历年县级及以上行政区划代码表，民政部：https://www.mca.gov.cn/n156/n186/index.html
我没有检查2018之前的年份的链接，我只更新了获取新数据必要的部分。其实作为用户，发现repo里面有已经整理好的csv数据已经很满足了！如果您有时间可以更新❤️
__还好你们之前将csv一起放入了repo🎉__

2023-12-18 15:14 UTC, Steve235lab commented
我认为我已经提交了必要的内容，如果code review没有问题，可以进行合并。

这个项目真的帮到了我很多！再次感谢！

如果仍然有需要帮助的地方，欢迎继续交流！

2023-12-20 18:06 UTC, lizy14 commented on rules-generated/code-changes.csv
> -1986-1987,332700,330900,舟山地区 -> 舟山市
这个文件的修改会直接影响结果，可能有必要搞清每个修改的原因。这一条规则为何被删除了？

2023-12-20 18:08 UTC, lizy14 commented on rules-generated/code-changes.csv
> +1987-1988,130504,441611,郊区
这条新增的规则有问题。名称都是“郊区”但根本不在同一个省，应该不是代码变更。下同。

2023-12-20 18:10 UTC, lizy14 commented on rules-generated/code-changes.csv
> -1987-1988,441000,460100,海口市
这条规则为何被删除了？1988 年海南省成立，广东省海口市变为海南省海口市，这条规则似乎正确反映了这一情况。

2023-12-20 18:10 UTC, lizy14 commented on rules-generated/code-changes.csv
> -1987-1988,441000,460100,海口市
下同

2023-12-20 18:12 UTC, lizy14 commented on rules-generated/code-changes.csv
> +2021-2022,350405,350405,沙县区
从这行开始往后的规则都是什么情况？变化前后的代码是相同的？

2023-12-20 18:14 UTC, lizy14 commented on rules-generated/name-changes.csv
> +1987-1988,339007,安徽省,义乌市
这一行和下一行似乎都是错误所致，“安徽省改名为义乌市”不合常识

2023-12-20 18:20 UTC, lizy14 commented on rules-generated/name-changes.csv
> -1990-1991,440502,同平区,龙湖区
这三行似乎应予保留？descriptions/source-a/1991.txt：汕头市安平区、同平区、公园区、金砂区、达濠区、郊区调整为龙湖区、金园区、升平区、达濠区。

2023-12-20 18:29 UTC, lizy14 requested changes
烦请再次核对 rules-handwritten/ 和 rules-generated/ 之下 2018 年以前部分的修改。这部分文件是人工手写的或者经过人工订正的，不宜直接用程序生成的新版本覆盖。当然，如果其中确有错误，欢迎修正。

2023-12-22 11:31 UTC, Steve235lab commented on rules-generated/name-changes.csv
> -1990-1991,440502,同平区,龙湖区
感谢您的耐心查正，对于2018年之前的数据，我已经回滚变更，目前我正在尝试更正2018年以后的数据，确实存在不少错误。

2023-12-24 05:40 UTC, lizy14 commented
为了支持任意两年间代码转换（#1），我今天做了一个小重构，提取了一个常量，需要请你在你的PR中将其更新为`2022`并解决合并冲突
https://github.com/lizy14/division-changes/blob/51ada1f21921b27f0d668a10dac721def0d90496/translate.py#L36

2023-12-25 12:01 UTC, Steve235lab commented
刚才我手动核对了2018-2022年的数据，现在应该是正确了

2023-12-26 02:43 UTC, Steve235lab commented
我新添加了一个测试，见: `tests/test_translate`，用来测试结果的正确性，即穷举所有年份`yyyy.csv`中的行政区划代码，使用`translate`函数来获取其当前的对应编码，然后检查该对应编码是否存在于最新一年的编码表`2022.csv`中，测试结果如下：

- [ ] year: 1984, code: 130504, name: 郊区 -> 130504 not in current code list
- [ ] year: 1984, code: 330511, name: 郊区 -> 330511 not in current code list
- [ ] year: 1984, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1984, code: 342700, name: 徽州地区 -> 242800 not in current code list
- [ ] year: 1984, code: 422129, name: 广济县 -> 412102 not in current code list
- [ ] year: 1984, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1984, code: 442200, name: 海南黎族苗族自治州 -> 442200 not in current code list
- [ ] year: 1984, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1984, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1984, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1984, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1984, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1985, code: 130504, name: 郊区 -> 130504 not in current code list
- [ ] year: 1985, code: 330511, name: 郊区 -> 330511 not in current code list
- [ ] year: 1985, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1985, code: 342700, name: 徽州地区 -> 242800 not in current code list
- [ ] year: 1985, code: 422129, name: 广济县 -> 412102 not in current code list
- [ ] year: 1985, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1985, code: 442200, name: 海南黎族苗族自治州 -> 442200 not in current code list
- [ ] year: 1985, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1985, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1985, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1985, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1985, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1986, code: 130504, name: 郊区 -> 130504 not in current code list
- [ ] year: 1986, code: 330511, name: 郊区 -> 330511 not in current code list
- [ ] year: 1986, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1986, code: 342700, name: 徽州地区 -> 242800 not in current code list
- [ ] year: 1986, code: 422129, name: 广济县 -> 412102 not in current code list
- [ ] year: 1986, code: 442200, name: 海南黎族苗族自治州 -> 442200 not in current code list
- [ ] year: 1986, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1986, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1986, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1986, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1986, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1986, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1987, code: 130504, name: 郊区 -> 130504 not in current code list
- [ ] year: 1987, code: 330511, name: 郊区 -> 330511 not in current code list
- [ ] year: 1987, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1987, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1987, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1987, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1987, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1987, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1987, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1988, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1988, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1988, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1988, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1988, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1988, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1988, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1989, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1989, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1989, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1989, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1989, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1989, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1989, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1990, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1990, code: 449001, name: 潮州市 -> 442102 not in current code list
- [ ] year: 1990, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1990, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1990, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1990, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1990, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1991, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1991, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1991, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1991, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1991, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1991, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1992, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1992, code: 449001, name: 顺德市 -> 442102 not in current code list
- [ ] year: 1992, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1992, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1992, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1992, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1992, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1993, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1993, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1993, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1993, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1993, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1993, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1994, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1994, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1994, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1994, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1994, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1994, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1995, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1995, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1995, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1995, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1995, code: 542137, name: 生达县 -> 542137 not in current code list
- [ ] year: 1995, code: 542528, name: 隆格尔县 -> 542528 not in current code list
- [ ] year: 1996, code: 340721, name: 铜陵县 -> 340704 not in current code list
- [ ] year: 1996, code: 542134, name: 盐井县 -> 542134 not in current code list
- [ ] year: 1996, code: 542135, name: 碧土县 -> 542135 not in current code list
- [ ] year: 1996, code: 542136, name: 妥坝县 -> 542136 not in current code list
- [ ] year: 1996, code: 542137, name: 生达县 -> 542137 not [...]

2023-12-26 03:26 UTC, Steve235lab commented
抱歉，之前没看到 @lizy14 在最近的提交中已经编写了一些单元测试，现在已经将新添加的全量测试放入`test_translate.py`

2023-12-26 09:14 UTC, lizy14 commented
非常感谢！你增加的这个测试用例非常有意义，查出了很多错误。

我对你上面给出的列表稍作了整理，以更便于阅读：
```
year: 1984-1987, code: 130504, name: 郊区, -> 130504 not in current code list
year: 1984-1987, code: 330511, name: 郊区, -> 330511 not in current code list
year: 1984-2014, code: 340721, name: 铜陵县, -> 340721 not in current code list
year: 1984-1986, code: 342700, name: 徽州地区, -> 342700 not in current code list
year: 1984-1986, code: 422129, name: 广济县, -> 422129 not in current code list
year: 1984-1992, code: 449001, name: 潮州市, -> 449001 not in current code list
year: 1984-1986, code: 442200, name: 海南黎族苗族自治州, -> 442200 not in current code list
year: 1984-1998, code: 542134, name: 盐井县, -> 542134 not in current code list
year: 1984-1998, code: 542135, name: 碧土县, -> 542135 not in current code list
year: 1984-1998, code: 542136, name: 妥坝县, -> 542136 not in current code list
year: 1984-1998, code: 542137, name: 生达县, -> 542137 not in current code list
year: 1984-1998, code: 542528, name: 隆格尔县, -> 542528 not in current code list
```

2023-12-27 16:50 UTC, Steve235lab commented
已经根据文字变更记录订正测试中发现的数据问题

2023-12-28 04:58 UTC, lizy14 approved these changes

2023-12-28 10:37 UTC, merged